<?php
/*
 Template Name: Project
 */

get_header();

?>

<div id="content-container" class="content-gradient">
<div id="full-width">

  <h2 id="content-title">
    >> 全球传播研究院研究人员主持项目 | 
    <font color="grey">PROJECT</font>
    <div class="hr"></div>
  </h2>

    <div class="table-content" >
      <table >
          <tr>
              <td>
                  项目来源
              </td>
              <td >
                  项目级别
              </td>
              <td>
                  项目名称
              </td>
              <td>
                  负责人
              </td>
              <td>
                  开始年份
              </td>
          </tr>
          <tr>
              <td >
                  国家社科基金
              </td>
              <td>
                  重大项目
              </td>
              <td>
                  传播当代中国价值观念与加强我国对外话语体系建设研究
              </td>
              <td>
                  单世联
              </td>
              <td>
                  2014
              </td>
          </tr>
          <tr>
              <td >
                  国家社科基金
              </td>
              <td>
                  重点项目
              </td>
              <td>
                  中华文化海外传播路径与形式创新研究
              </td>
              <td>
                  张国良
              </td>
              <td>
                  2014
              </td>
          </tr>
          <tr>
              <td >
                  国家社科基金
              </td>
              <td>
                  重点项目
              </td>
              <td>
                  文化产业社会效益研究
              </td>
              <td>
                  单世联
              </td>
              <td>
                  2014
              </td>
          </tr>
          <tr>
              <td >
                  国家社科基金
              </td>
              <td>
                  重大项目
              </td>
              <td>
                  提升我国文化产品国际竞争力的路径与策略研究
              </td>
              <td>
                  李本乾
              </td>
              <td>
                  2013
              </td>
          </tr>
          <tr>
              <td >
                  国家社科基金
              </td>
              <td>
                  一般项目
              </td>
              <td>
                  基于大数据的突发危机中非官方正能量信息的挖掘与传播研究
              </td>
              <td>
                  薛可
              </td>
              <td>
                  2013
              </td>
          </tr>
          <tr>
              <td >
                  国家社科基金
              </td>
              <td>
                  重点项目
              </td>
              <td>
                  中国特色政治传播战略理论与策略体系研究
              </td>
              <td>
                  李本乾
              </td>
              <td>
                  2011
              </td>
          </tr>
          <tr>
              <td >
                  国家社科基金
              </td>
              <td>
                  青年项目
              </td>
              <td>
                  微博客舆情监测与主动引导机制
              </td>
              <td>
                  禹卫华
              </td>
              <td>
                  2011
              </td>
          </tr>
          <tr>
              <td >
                  国家社科基金
              </td>
              <td>
                  青年项目
              </td>
              <td>
                  “十二五”时期推进文化体制改革创新研究
              </td>
              <td>
                  凌金铸
              </td>
              <td>
                  2011
              </td>
          </tr>
          <tr>
              <td >
                  国家社科基金
              </td>
              <td>
                  一般项目
              </td>
              <td>
                  被报道的中国：基于国家形象理论的长程实证研究
              </td>
              <td>
                  葛  岩
              </td>
              <td>
                  2011
              </td>
          </tr>
          <tr>
              <td>国家社科基金</td>
              <td>一般项目</td>
              <td>西方文化产业理论发展研究</td>
              <td>单世联</td>
              <td>2010</td>
          </tr>
          <tr>
              <td>国家社科基金</td>
              <td>一般项目</td>
              <td>手机媒体新闻传播效果研究</td>
              <td>张国良</td>
              <td>2009</td>
          </tr>
          <tr>
              <td>国家社科基金</td>
              <td>一般项目</td>
              <td>境外资本进入中国传媒市场的现状、影响与监管对策</td>
              <td>李本乾</td>
              <td>2009</td>
          </tr>
          <tr>
              <td>国家社科基金</td>
              <td>重大项目</td>
              <td>突发事件网络舆情预警指标体系研究</td>
              <td>谢耘耕</td>
              <td>2009</td>
          </tr>
          <tr>
              <td>国家社科基金</td>
              <td>青年项目</td>
              <td>3G手机媒体采纳与扩散研究</td>
              <td>李晓静</td>
              <td>2009</td>
          </tr>
          <tr>
              <td>国家自然科学基金</td>
              <td>面上项目</td>
              <td>新媒体沟通形态与员工沟通满意度、合作绩效的关系研究</td>
              <td>姜进章</td>
              <td>2009</td>
          </tr>
          <tr>
              <td>国家社科基金</td>
              <td>青年项目</td>
              <td>公民新闻在中国的现状、影响与发展研究</td>
              <td>王  昊</td>
              <td>2008</td>
          </tr>
          <tr>
              <td>国家社科基金</td>
              <td>一般项目</td>
              <td>沟通与和谐：汉语全球传播的渠道与策略研究</td>
              <td>姚君喜</td>
              <td>2007</td>
          </tr>
          <tr>
              <td>全国教育科学规划课题</td>
              <td>青年项目</td>
              <td>青少年控烟态度与行为及学校控烟教育研究</td>
              <td>王  茜</td>
              <td>2011</td>
          </tr>
          <tr>
              <td>部委级科研项目</td>
              <td>重点课题</td>
              <td>中国电影“走出去”路径与策略研究</td>
              <td>李亦中</td>
              <td>2009</td>
          </tr>
          <tr>
              <td>部委级科研项目</td>
              <td>后期资助重大项目</td>
              <td>江南城市群的历史源流与都市文化研究</td>
              <td>刘士林</td>
              <td>2010</td>
          </tr>
          <tr>
              <td>部委级科研项目</td>
              <td>重大攻关项目</td>
              <td>我国文化产业发展战略研究</td>
              <td>胡惠林</td>
              <td>2008</td>
          </tr>
          <tr>
              <td>部委级科研项目</td>
              <td>一般项目</td>
              <td>中国电影评价系统研究</td>
              <td>李亦中</td>
              <td>2009</td>
          </tr>
          <tr>
              <td>部委级科研项目</td>
              <td>哲社发展报告项目</td>
              <td>中国都市化进程研究报告</td>
              <td>刘士林</td>
              <td>2011</td>
          </tr>
          <tr>
              <td>部委级科研项目</td>
              <td>哲社发展报告（培育）</td>
              <td>中国传媒国际竞争力研究报告</td>
              <td>李本乾</td>
              <td>2011</td>
          </tr>
          <tr>
              <td>部委级科研项目</td>
              <td>哲社发展报告（培育）</td>
              <td>中国社会舆情与危机管理报告</td>
              <td>谢耘耕</td>
              <td>2011</td>
          </tr>
          <tr>
              <td>部委级科研项目</td>
              <td>一般项目</td>
              <td>生态危机报道与可持续发展：环境新闻在我国面临的问题与对策研究</td>
              <td>王积龙</td>
              <td>2011</td>
          </tr>
          <tr>
              <td>部委级科研项目</td>
              <td>一般项目</td>
              <td>我国网络传播的PEST外部协同治理机制研究</td>
              <td>李本乾</td>
              <td>2009</td>
          </tr>
          <tr>
              <td>部委级科研项目</td>
              <td>重点课题</td>
              <td>三网融合条件下我国云视听的技术平台与内容产业发展模式研究</td>
              <td>李本乾</td>
              <td>2011</td>
          </tr>
          <tr>
              <td>省级（哲学）社科基金项目</td>
              <td>重大项目</td>
              <td>上海加强文化建设增强城市文化软实力研究</td>
              <td>李本乾</td>
              <td>2009</td>
          </tr>
          <tr>
              <td>省级（哲学）社科基金项目</td>
              <td>系列重大课题</td>
              <td>互联网信息传播及其治理研究</td>
              <td>李本乾</td>
              <td>2009</td>
          </tr>
          <tr>
              <td>省级（哲学）社科基金项目</td>
              <td>一般项目</td>
              <td>高校网络舆论领袖的形成、作用和管理研究</td>
              <td>薛  可</td>
              <td>2009</td>
          </tr>
          <tr>
              <td>省级（哲学）社科基金项目</td>
              <td>一般课题</td>
              <td>我国医患关系中的传播因素的实证研究</td>
              <td>戴永明</td>
              <td>2011</td>
          </tr>
          <tr>
              <td>省级（哲学）社科基金项目</td>
              <td>专题研究课题</td>
              <td>中国国家文化安全战略研究</td>
              <td>胡惠林</td>
              <td>2011</td>
          </tr>
          <tr>
              <td>省级高校人文社科研究项目</td>
              <td>重点课题</td>
              <td>三网融合背景下推进上海数字内容产业发展的政策研究</td>
              <td>李本乾</td>
              <td>2011</td>
          </tr>


      </table>
    </div>
              


  </div>
</div>

<div class="clear"></div>
  </div>
<?php
get_footer();
?>
